version: '3.7.0'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: thouCoder
      WORDPRESS_DB_PASSWORD: 1453
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./thmese:/var/www/html/wp-content/themes  

  db:
    image: mysql:oracle
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: thouCoder
      MYSQL_PASSWORD: 1453
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - .db:/var/lib/mysql
volumes:
  wordpress:
  db: